'use client';
import {useMemo,useState} from 'react';
import {ArrowLeft,BookOpen,Check,ChevronRight,Headphones,House,RotateCcw,Search,Volume2,PenLine,ClipboardCheck} from 'lucide-react';
import {lessons} from '@/data/lessons';import {vocab} from '@/data/vocab';import {extraVocab} from '@/data/extra';import type {Lesson,Vocab} from '@/data/types';import {useStudyState} from '@/lib/storage';import {speak} from '@/lib/speak';import StrokeBox from './StrokeBox';
import {phonetics} from '@/data/phonetics';
type Screen='home'|'lesson'|'read'|'cards'|'one'|'write'|'exam'|'phonetics';
const allLessons:Lesson={id:0,hanzi:'บท 1–8',pinyin:'',th:'ทุกบท',bookPages:'',topics:[],vocabIds:[],dialogue:[],grammar:[]};
export default function Reviewer(){
 const [screen,setScreen]=useState<Screen>('home');const [lesson,setLesson]=useState<Lesson>(lessons[0]);const [state,setState,ready]=useStudyState();const [index,setIndex]=useState(0);const [revealed,setRevealed]=useState(false);const [search,setSearch]=useState('');const [notice,setNotice]=useState('');const [writingMode,setWritingMode]=useState<'animate'|'quiz'>('animate');const [phoneticUnit,setPhoneticUnit]=useState<'P1'|'P2'|'P3'>('P1');const [answers,setAnswers]=useState<Record<string,number>>({});
 const all=[...vocab,...extraVocab];const scoped=useMemo(()=>all.filter(v=>(state.settings.scope==='all'||v.category!=='extra')&&(lesson.id===0||screen==='home'||screen==='exam'||v.lessons.includes(lesson.id))&&(!search||`${v.hanzi}${v.pinyin}${v.th}${v.en}`.toLowerCase().includes(search.toLowerCase()))),[state.settings.scope,lesson,screen,search]);
 const queue=scoped.length?scoped:all.slice(0,1);const item=queue[index%queue.length];const count=Object.values(state.known).filter(v=>v==='known').length;
 const back=()=>{setScreen(screen==='lesson'?'home':screen==='read'||screen==='cards'||screen==='one'||screen==='write'?'lesson':'home');setRevealed(false)};
 const setKnown=(v:Vocab,status:'known'|'unknown')=>setState(s=>({...s,known:{...s.known,[v.id]:status},quizWrong:status==='unknown'?[v.id,...s.quizWrong.filter(x=>x!==v.id)]:s.quizWrong.filter(x=>x!==v.id)}));
 const next=()=>{setIndex(i=>(i+1)%queue.length);setRevealed(false)};
 const play=(hanzi:string)=>{if(!speak(hanzi)){setNotice('อุปกรณ์นี้ยังไม่มีเสียงภาษาจีน ลองเปิดใน Chrome หรือ Safari');setTimeout(()=>setNotice(''),3500)}};
 return <main className="shell">
  <header className="top"><button className="iconBtn" aria-label="กลับหน้าก่อน" onClick={back}>{screen==='home'?<House/>:<ArrowLeft/>}</button><div><div className="eyebrow">LNG275 · MIDTERM</div><strong>ทบทวนภาษาจีน</strong></div><span className="miniCount">{count}<small> รู้แล้ว</small></span></header>
  {notice&&<div className="notice" role="status">{notice}</div>}
  {screen==='home'&&<>
   <section className="hero"><div className="heroText"><span className="tag">บทที่ 1–8</span><h1>วันนี้อยาก<br/>ทบทวนอะไรดี?</h1><p>เลือกบทหรือโหมดที่อยากฝึกได้เลย</p></div><div className="heroArt" aria-hidden="true"><span lang="zh-CN">你好</span><i>✿</i></div></section>
   <section className="progressCard"><div><b>ความคืบหน้าของคุณ</b><span>{count} / {vocab.length} คำที่จำได้</span></div><div className="track"><i style={{width:`${Math.min(count/vocab.length*100,100)}%`}}/></div></section>
   <div className="sectionTitle"><h2>ฝึกสัทศาสตร์</h2><span>P1–P3</span></div><div className="phoneticGrid">{(['P1','P2','P3'] as const).map((unit,i)=><button key={unit} onClick={()=>{setPhoneticUnit(unit);setScreen('phonetics')}}><span>{unit}</span><b>{['สระและวรรณยุกต์','พยัญชนะต้น','เสียงและการเปลี่ยนเสียง'][i]}</b><ChevronRight size={16}/></button>)}</div>
   <div className="sectionTitle"><h2>เลือกบทเรียน</h2><span>บท 1–8</span></div><div className="lessonGrid">{lessons.map(l=><button className="lessonTile" key={l.id} onClick={()=>{setLesson(l);setScreen('lesson')}}><span className="lessonNo">บทที่ {l.id}</span><b lang="zh-CN">{l.hanzi}</b><span>{l.th}</span><ChevronRight size={17}/></button>)}</div>
   <div className="sectionTitle"><h2>ฝึกแบบรวดเร็ว</h2></div><div className="modeGrid"><button onClick={()=>{setLesson(allLessons);setScreen('cards')}}><BookOpen/><b>แฟลชการ์ด</b><span>จำคำศัพท์ทีละใบ</span></button><button onClick={()=>{setLesson(allLessons);setScreen('one')}}><Search/><b>ทีละคำ</b><span>ค้นหาและอ่านทวน</span></button><button onClick={()=>{setLesson(allLessons);setScreen('write')}}><PenLine/><b>ฝึกเขียน</b><span>ดูและลองเขียน</span></button><button onClick={()=>setScreen('exam')}><ClipboardCheck/><b>ข้อมูลสอบ</b><span>เช็กลิสต์เตรียมสอบ</span></button></div>
  </>}
  {screen==='lesson'&&<><section className="lessonHero"><span className="tag">บทที่ {lesson.id}</span><h1 lang="zh-CN">{lesson.hanzi}</h1><p>{lesson.pinyin} · {lesson.th}</p><div className="topics">{lesson.topics.map(t=><span key={t}>{t}</span>)}</div></section><div className="sectionTitle"><h2>เริ่มทบทวน</h2></div><div className="actionList"><button onClick={()=>{setScreen('read');setIndex(0)}}><BookOpen/><span><b>อ่านเนื้อหาบท</b><small>คำศัพท์ · บทสนทนา · ไวยากรณ์</small></span><ChevronRight/></button><button onClick={()=>{setScreen('cards');setIndex(0)}}><RotateCcw/><span><b>แฟลชการ์ด</b><small>{lesson.vocabIds.length} คำในบทนี้</small></span><ChevronRight/></button><button onClick={()=>{setScreen('one');setIndex(0)}}><Search/><span><b>ทวนทีละคำ</b><small>ค้นคำศัพท์และฟังเสียงอ่าน</small></span><ChevronRight/></button><button onClick={()=>{setScreen('write');setIndex(0)}}><PenLine/><span><b>ฝึกลำดับขีด</b><small>ดูภาพเคลื่อนไหวและฝึกลาก</small></span><ChevronRight/></button></div></>}
  {screen==='read'&&<><PageTitle title={`บทที่ ${lesson.id} · ${lesson.th}`} /><div className="contentCard"><h2>คำศัพท์</h2>{lessonWords(lesson,all).map(v=><article className="wordRow" key={v.id}><div><b lang="zh-CN">{v.hanzi}</b><span>{v.pinyin}</span></div><div><span lang="th">{v.th}</span><small>{v.en}</small></div><button className="tinyIcon" aria-label={`ฟังคำว่า ${v.hanzi}`} onClick={()=>play(v.hanzi)}><Volume2 size={19}/></button></article>)}</div><div className="contentCard"><h2>บทสนทนา</h2>{lesson.dialogue.map((d,i)=><article className="dialogue" key={i}><span className="speaker">{d.speaker}</span><div><b lang="zh-CN">{d.hanzi}</b><small>{d.pinyin}</small><span>{d.th}</span></div><button className="tinyIcon" aria-label="ฟังประโยค" onClick={()=>play(d.hanzi)}><Volume2 size={18}/></button></article>)}</div><div className="contentCard"><h2>ไวยากรณ์</h2>{lesson.grammar.map((g,i)=><article className="grammar" key={i}><h3>{g.title}</h3><code>{g.pattern}</code><p>{g.explainTh}</p>{g.examples.map((e,j)=><div className="example" key={j}><b lang="zh-CN">{e.hanzi}</b><span>{e.pinyin}</span><span>{e.th}</span></div>)}</article>)}</div></>}
  {(screen==='cards'||screen==='one')&&<><PageTitle title={screen==='cards'?'แฟลชการ์ด':'ทวนทีละคำ'} /><label className="searchbox"><Search/><input value={search} onChange={e=>{setSearch(e.target.value);setIndex(0)}} placeholder="ค้นหาคำศัพท์" aria-label="ค้นหาคำศัพท์"/></label><div className="cardCounter">{index%queue.length+1} / {queue.length}</div><section className="flashCard"><div className="cardTop"><span>{item.category==='core'?'คำหลัก':item.category==='phrase'?'วลี':item.category==='extra'?'คำเสริม':'คำในบริบท'}</span><button className="tinyIcon" aria-label="ฟังเสียงอ่าน" onClick={()=>play(item.hanzi)}><Volume2/></button></div><b className="bigHanzi" lang="zh-CN">{item.hanzi}</b>{state.settings.showPinyin&&<span className="cardPinyin">{item.pinyin}</span>}{revealed&&<div className="cardAnswer"><b lang="th">{item.th}</b><span>{item.en}</span>{item.pos&&<small>{item.pos}</small>}</div>}<button className="primary" onClick={()=>setRevealed(r=>!r)}>{revealed?'ซ่อนคำตอบ':'แสดงคำตอบ'}</button></section>{revealed&&<div className="knowBtns"><button onClick={()=>{setKnown(item,'unknown');next()}}>ยังจำไม่ได้</button><button onClick={()=>{setKnown(item,'known');next()}}><Check size={18}/> จำได้แล้ว</button></div>}<div className="settings"><label><input type="checkbox" checked={state.settings.showPinyin} onChange={e=>setState(s=>({...s,settings:{...s.settings,showPinyin:e.target.checked}}))}/> แสดงพินอิน</label><label><input type="checkbox" checked={state.settings.scope==='all'} onChange={e=>setState(s=>({...s,settings:{...s.settings,scope:e.target.checked?'all':'core'}}))}/> รวมคำเสริม</label></div><button className="nextBtn" onClick={next}>คำถัดไป <ChevronRight/></button></>}
  {screen==='write'&&<><PageTitle title="ฝึกลำดับขีด" /><div className="writeCard"><span className="tag">{index%queue.length+1} / {queue.length}</span><h2 lang="zh-CN">{item.hanzi}</h2><p>{item.pinyin} · {item.th}</p><div className="modeSwitch"><button className={writingMode==='animate'?'selected':''} onClick={()=>setWritingMode('animate')}>ดูจังหวะ</button><button className={writingMode==='quiz'?'selected':''} onClick={()=>setWritingMode('quiz')}>ลองลากเขียน</button></div><div className="strokeRow">{Array.from(item.hanzi.matchAll(/[\u4e00-\u9fff]/gu)).map((m,i)=><StrokeBox key={`${item.id}-${i}`} char={m[0]} size={145} mode={writingMode}/>)}</div><p className="soft">ลากเส้นตามลำดับขีดหรือดูตัวอย่างการเขียน</p><button className="primary" onClick={()=>next()}>คำถัดไป</button></div></>}
  {screen==='exam'&&<><PageTitle title="เตรียมตัวสอบ"/><section className="examCard"><span className="tag">LNG275 · บท 1–8</span><h1>เช็กความพร้อม</h1><p>ข้อมูลตามสรุปที่ให้ไว้ในไฟล์ต้นทาง</p><div className="examInfo"><span>วันสอบ</span><b>03/10/69 · 09:00–11:00</b><span>รูปแบบ</span><b>ข้อกาและข้อเขียน · 75 ข้อ</b><span>ขอบเขต</span><b>บทที่ 1–8 · 25 คะแนน</b></div>{['ทวนคำศัพท์ให้ครบ','ฝึกเขียนพินอินมีวรรณยุกต์','ฝึกเรียงประโยคภาษาจีน','ทบทวนบทสนทนาและไวยากรณ์'].map((x,i)=><label className="checkline" key={x}><input type="checkbox" checked={!!state.examChecklist[String(i)]} onChange={e=>setState(s=>({...s,examChecklist:{...s.examChecklist,[String(i)]:e.target.checked}}))}/>{x}</label>)}<button className="clearBtn" onClick={()=>{if(confirm('ล้างความคืบหน้าและการตั้งค่าทั้งหมดหรือไม่?')){localStorage.removeItem('lng275:v1');setState({known:{},quizWrong:[],settings:{showPinyin:true,showMeaning:true,scope:'core',shuffle:false},examChecklist:{}})}}}>ล้างความคืบหน้า</button></section></>}
  {screen==='phonetics'&&<><PageTitle title={`สัทศาสตร์ ${phoneticUnit}`} tag={phoneticUnit} /><div className="unitSwitch">{(['P1','P2','P3'] as const).map(u=><button className={u===phoneticUnit?'selected':''} key={u} onClick={()=>{setPhoneticUnit(u);setAnswers({})}}>{u}</button>)}</div>{phonetics.filter(p=>p.unit===phoneticUnit).map((p,i)=><section className="contentCard phoneticCard" key={`${p.unit}-${i}`}><span className="tag">{p.unit}</span><h2>{p.title}</h2><div className="phoneticDisplay">{p.display}</div><p>{p.summaryTh}</p>{p.examples.length>0&&<div className="examples">{p.examples.map((e,j)=><span key={j} lang="zh-CN">{e}</span>)}</div>}{p.quiz.map(q=><div className="question" key={q.id}><b>{q.question}</b><div>{q.choices.map((choice,j)=><button className={answers[q.id]===j?'chosen':''} onClick={()=>setAnswers(a=>({...a,[q.id]:j}))} key={j}>{j+1}. {choice}</button>)}</div>{answers[q.id]!==undefined&&<p className={answers[q.id]===q.answerIndex?'right':'wrong'}>{answers[q.id]===q.answerIndex?'ถูกต้อง · ':'ลองทบทวนอีกครั้ง · '}{q.explainTh}</p>}</div>)}</section>)}</>}
  <footer>ทบทวนจากเนื้อหาในไฟล์สรุป · <span lang="zh-CN">汉语教程第一册上</span></footer>
 </main>
 function PageTitle({title,tag=lesson.hanzi}:{title:string;tag?:string}){return <div className="pageTitle"><span className="tag">{tag}</span><h1>{title}</h1></div>}
}
function lessonWords(lesson:Lesson,all:Vocab[]){return lesson.vocabIds.map(id=>all.find(v=>v.id===id)).filter((v):v is Vocab=>!!v)}
