import { readFileSync,existsSync } from 'node:fs';
const read=<T>(p:string)=>JSON.parse(readFileSync(new URL(p,import.meta.url),'utf8')) as T;
type V={id:string;hanzi:string;pinyin:string;pinyinNum?:string;th:string;en:string;lessons:number[]};
const words=read<V[]>('../src/data/vocab.json');const lessons=read<{id:number;vocabIds:string[]}[]>('../src/data/lessons.json');
const errors:string[]=[];if(words.length!==204)errors.push(`expected 204 main vocabulary entries, received ${words.length}`);
const ids=new Set<string>();for(const w of words){if(ids.has(w.id))errors.push(`duplicate id ${w.id}`);ids.add(w.id);for(const k of ['hanzi','pinyin','th','en'] as const)if(!w[k]?.trim())errors.push(`${w.id} missing ${k}`);if(w.lessons.some(n=>n<1||n>8))errors.push(`${w.id} has a lesson outside 1–8`)}
for(const l of lessons)for(const id of l.vocabIds)if(!ids.has(id))errors.push(`lesson ${l.id} references missing vocab ${id}`);
const chars=new Set(words.flatMap(w=>[...w.hanzi].filter(c=>/[\u4e00-\u9fff]/u.test(c))));const missing=existsSync(new URL('../public/hanzi-data/_missing.json',import.meta.url))?new Set<string>(read<string[]>('../public/hanzi-data/_missing.json')):new Set<string>();const noFile=[...chars].filter(c=>!existsSync(new URL(`../public/hanzi-data/${c}.json`,import.meta.url))&&!missing.has(c));if(noFile.length)errors.push(`stroke data has neither file nor missing-list entry: ${noFile.join('')}`);
const phonetics=read<{unit:string;quiz:{id:string;choices:string[];answerIndex:number}[]}[]>('../src/data/phonetics.json');if(phonetics.length!==23)errors.push(`expected 23 phonetics topics, received ${phonetics.length}`);if(phonetics.reduce((n,p)=>n+p.quiz.length,0)!==31)errors.push('phonetics quiz count must be 31');for(const p of phonetics)for(const q of p.quiz)if(q.answerIndex<0||q.answerIndex>=q.choices.length)errors.push(`invalid answer index in ${q.id}`);
const extras=read<V[]>('../src/data/extra.json');if(extras.length!==14)errors.push(`expected 14 distinct image extras, received ${extras.length}`);if(words.some(w=>!w.pinyinNum))errors.push('one or more main vocabulary records lack numbered pinyin');
console.log(`Vocabulary: ${words.length}; lessons: ${lessons.length}; phonetics: ${phonetics.length} topics / 31 questions; extras: ${extras.length}; unique Hanzi: ${chars.size}; explicit stroke misses: ${missing.size}`);if(errors.length){console.error(errors.join('\n'));process.exitCode=1}else console.log('Data verification passed.');
